### ISSUE TITLE
How can I get the .stats files?

### ISSUE THREAD

**Issue by WangYunHong98** [faskowit/multiAtlasTT#14]
Hi @faskowit 

I used multiAtlasTT, it's amazing!

I have a question that how can I accquire ```stats``` directory of file like freesurfer output?

Best,
Yunhong

**Comment by faskowit** [comment]
Hi @WangYunHong98 -- Thanks for your interest!  There is no way to compute exactly the same output as what's in the `stats` directory... however, checkout the FreeSurfer function: `mris_anatomical_stats`.  In the help documentation there, you'll see the suggestion: 

```	mris_anatomical_stats -a subjid/label/lh.aparc.annot -b subjid lh```
you might try this out, substituting your own data and using the `.annot` file that multiAtlasTT makes.  Also, make sure FreeSurfer subjects dir is property setup to be pointing at your data. 

Otherwise, you can compute other volume-based stats with the FreeSurfer function `mri_segstats`

I hope this helps! 

--Josh

**Comment by WangYunHong98** [comment]
Hi @faskowit 

Thanks for your help.

I wrote a code to implement this process, please help me to see if it is correct.

```
# Set atlasList
export atlasList="schaefer400-yeo17"

# Extract the subject name from the input directory
subj=$(basename $inputFSDir)

# Set the SUBJECTS_DIR environment variable
export SUBJECTS_DIR=$(dirname ${inputFSDir})/

# Define the hemispheres to process
HEMISPHERE=("lh" "rh")

# Process each hemisphere
for atlas in "${atlasList[@]}"; do
    for hemi in "${HEMISPHERE[@]}"; do
    # Run the mris_anatomical_stats command and log the output
        ${FREESURFER_HOME}/bin/mris_anatomical_stats \
        -a ${annotDir}/${atlas}/${hemi}.${subj}_${atlas}.annot \
        -f ${outputDir}/${hemi}.400parc.stats \
        -b \
        ${subj} \
        ${hemi} >> ${outputDir}/output.log 2>&1
    done
done
```

Best,
Yunhong

**Comment by WangYunHong98** [comment]
Hi @faskowit 

I have another question, if I want to use **Schaefer1000-17Net** as a target parcellation (see below from https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations), should I run ```maTT_labelTrnsfr.sh``` to generate the corresponding ```*h.atlas_colortab.txt``` and ```LUT_atlas.txt``` before running ```maTT_main.sh```?

![image](https://github.com/faskowit/multiAtlasTT/assets/104638954/3192ef1d-c1d8-4c9a-b07a-69c930d8e32a)

Also, if I want to apply ```gcs```, should I run ```maTT2_caLabelTrain_example.sh``` to generate the corresponding ```*h.atlas_fsversion.gcs``` before running ```maTT2_applyGCS.sh```?

Best,
Yunhong

**Comment by faskowit** [comment]
The script you wrote looks good to me -- does the code run smoothly and does it populate the `.stats` file? 

Generating the gcs files is a long and involved process -- I've provided pre-trained gcs files in a link in the homepage documentation.  And I have an example script of how the process looks, after running maTT1 on all your subjects: https://github.com/faskowit/multiAtlasTT/blob/master/src/maTT2_caLabelTrain_example.sh  Ideally, you would provide hand-edited and super precise `.annot` files for training... but, as a warning, I did not do this for my trained files. However, I would also recommend checking out the gcs files provided directly from the Yeo lab.  You can find those files, and good documentation, here: https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/project_to_individual  

I hope this helps!

**Comment by WangYunHong98** [comment]
Thank you @faskowit 

The script worked well to me, populating the ```.stats``` files.

Yeo lab provided ```.gcs``` files which is useful to me. Could I directly use Yeo's ```.gcs``` file of Schafer400-7Net then apply it to your ```maTT2_applyGCS.sh``` ?

Best,
Yunhong

**Comment by faskowit** [comment]
You can go ahead and try it out -- I'm not sure if it will work or not!  You will have to make sure that the `.gcs` file is in the place that the script expect it to be.  Otherwise, you might also benefit from following the instructions on the Yeo lab github if `maTT2_applyGCS.sh` does not seem to work
