### ISSUE TITLE
Extract morphometric index from T1 and DWI using Schefer400 atlas

### ISSUE THREAD

**Issue by WangYunHong98** [faskowit/multiAtlasTT#15]
Hi @faskowit ,

I am working with tht extraction of morphometric analysis using Schefer400-7net atlas.

First, the FreeSurfer reconstruction was performed using your amazing tool. Individual ```.annot``` files were generated using the Schafer400-7net ```.gcs``` files and then individually parceled to extract surface area, cortical thickness, gray matter volume, Gaussian curvature, and mean curvature.

Second, I'm going to use DWI images to generate fractional anisotropy and mean diffusivity and also want to parcel them to Schefer400-7net to generate corresponding index like the way of T1 images for each subject. I wonder if this is feasible?

Best,
Yunhong

**Comment by faskowit** [comment]
Hello -- are you planning to run tractography and then extract FA and MD along the streamlines?  Otherwise, I do not think your question makes 100% sense to me.  There are a handful of papers that extract DWI metrics in the gray matter, but they use specialized DWI acquisitions: for example https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6706419/.  So overall, the feasibility depends on the data you are using!

**Comment by WangYunHong98** [comment]
Hi @faskowit 

Yes, I would like to run tractography and then extract FA and MD along the streamlines.

I'm going to extract morphometric index using in this paper https://linkinghub.elsevier.com/retrieve/pii/S0896627317310929. Different from the paper using DK308 atlas, I want to use Schaefer400-7net. 

Best,
Yunhong

**Comment by faskowit** [comment]
ok yes indeed, good luck with that!  I hope you get nice results!

**Comment by WangYunHong98** [comment]
Thank you for the detailed answer! @faskowit
