### ISSUE TITLE
a question about hcp-mmp data

### ISSUE THREAD

**Issue by sheyma** [faskowit/multiAtlasTT#4]
Hi,

I am looking for the fsaverge5 resampled versions of  lh.hcp-mmp.annot (and also rh.hcp-mmp.annot) files in your repository. 

/atlas_data/hcp-mmp has *annot files, that are sampled across fsaverage 164k. Is there an easy way to downsaple them to fsaverage5 (10k)?

Thanks in advance!

**Comment by faskowit** [comment]
Hi! Thanks for reaching out! 

First of all, I think I'd recommend hcp-mmp-b, because it was transferred to fsaverage in a slightly different way, based on some HCP advice (but honestly, you can try both annots and see what suits you better). I think a FreeSurfer command like this should do the trick, assuming your FreeSurfer is all setup with the correct SUBJECT_DIR path (which should point to $FREESURFER_HOME/subjects I think). 

`mri_surf2surf --srcsubject fsaverage --trgsubject fsaverage5 --hemi lh --sval-annot /atlas_data/lh.hcp-mmp.annot --tval ./lh.hcp-mmp_fsaverage5.annot`

Also, just want to let you know that the HCP authors warn against doing this -- as they support their own surface files with more confidence.  If you'd like to map from their surface space, directly to fsaverage5, you can check out the instructions here: https://wiki.humanconnectome.org/display/PublicData/HCP+Users+FAQ?preview=%2F63078513%2F87590453%2FResampling-FreeSurfer-HCP.pdf

**Comment by sheyma** [comment]
Hi,

It wast great to see you reply! Thanks.

I tried $mri_surf2surf command as you wrote, and "lh.hcp-mmp_fsaverage5.annot" was generated successfully. All worked out, thanks again!

Actually, the reason of such a sampling was to run some plotting functions faster ;) The HCP links were also very helpful.

And, apologies for my late response..

All the best!
