### ISSUE TITLE
Description of parcels ROIs

### ISSUE THREAD

**Issue by AlvaroDeleglise** [faskowit/multiAtlasTT#5]
Hi! First of all, thank you so much for providing the .gcs files of almost all the atlases that are contained the .figshare links. I usually just use these files to run a specific parcellation on individual subject space by using the mris_ca_label function of freesurfer.
I just want to ask you if there are some files that provide a more friendly or semantic description of the atlases parcels. For example, I run both the Shen and HCP-MMP-B parcellations on a subject, but they lack a meaningfull description of the ROIs when loading the annot files on freeview. In Shen, the annots files just say, for example, right_parc_42, right_parc43, etc. I HCP, the annots files and labels seems to lack of any kind of sense. 
I really appreciate your help.

Cheers.

**Comment by faskowit** [comment]
Hi, 

Thanks for your interest in the tool!  In the Nature paper where the hcp-mmp parcellation was proposed, they have a supplementary table with the names and citations for specific areas in this document in Table 1 (all the way at the end): https://static-content.springer.com/esm/art%3A10.1038%2Fnature18933/MediaObjects/41586_2016_BFnature18933_MOESM330_ESM.pdf Further, this document describes each region from a neuroanatomical perspective. Otherwise, I usually just google the names of the regions I find that come up in analyses.

For the shen, these data are provided just for parcellation, as the names that I placed in the .annot and .gca files are meaningless.  You might be interested in the original paper here: https://pubmed.ncbi.nlm.nih.gov/23747961/  but I am afraid I cannot relate the original regions (volume space) to the regions in the data here; it would have to be done computationally. 

I hope these little bits of information helps. Cheers!
